const portfolios = [
    {
        jenis_usaha: "Agrobisnis",
        customer_proyek: "PT Sriwijaya Palm Oil",
        keterangan: "Perkebunan Kelapa Sawit",
        lokasi: "Sumatera Selatan",
    },
    {
        jenis_usaha: "Agrobisnis",
        customer_proyek: "PT Selatan Agro Makmur Lestari",
        keterangan: "Perkebunan Kelapa Sawit",
        lokasi: "Sumatera Selatan",
    },
    {
        jenis_usaha: "Agrobisnis",
        customer_proyek: "PT Persada Sawit Mas",
        keterangan: "Perkebunan Kelapa Sawit",
        lokasi: "Sumatera Selatan",
    },
    {
        jenis_usaha: "BUMN",
        customer_proyek: "PDAM Mukomuko",
        keterangan: "PDAM",
        lokasi: "Bengkulu",
    },
    {
        jenis_usaha: "BUMN",
        customer_proyek: "PDAM Tirta Bukit Sulap",
        keterangan: "PDAM",
        lokasi: "Lubuklinggau",
    },
    {
        jenis_usaha: "BUMN",
        customer_proyek: "PDAM Tirta Musi",
        keterangan: "PDAM",
        lokasi: "Palembang",
    },
    {
        jenis_usaha: "BUMN",
        customer_proyek: "PDAM Tirta Randik",
        keterangan: "PDAM",
        lokasi: "Sekayu (Sumsel)",
    },
    {
        jenis_usaha: "BUMN",
        customer_proyek: "PDAM Tirta Dharma Ayu",
        keterangan: "PDAM",
        lokasi: "Indramayu",
    },
    {
        jenis_usaha: "BUMN",
        customer_proyek: "PDAM Biak",
        keterangan: "PDAM",
        lokasi: "Biak",
    },
    {
        jenis_usaha: "BUMN",
        customer_proyek: "PDAM Jayapura",
        keterangan: "PDAM",
        lokasi: "Jayapura",
    },
    {
        jenis_usaha: "BUMN",
        customer_proyek: "PDAM Merauke",
        keterangan: "PDAM",
        lokasi: "Merauke",
    },
    {
        jenis_usaha: "BUMN",
        customer_proyek: "PDAM Tirta Mayang",
        keterangan: "PDAM",
        lokasi: "Jambi",
    },
    {
        jenis_usaha: "BUMN",
        customer_proyek: "PDAM Sungailiat",
        keterangan: "PDAM",
        lokasi: "Bangka",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Air Manado",
        keterangan: "ME",
        lokasi: "Manado",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Atamara Teknik Makmur",
        keterangan: "ME",
        lokasi: "Jakarta",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Austindo Energi",
        keterangan: "ME",
        lokasi: "Jakarta",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Bina Raya Gema Reksa",
        keterangan: "ME",
        lokasi: "Medan",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Capruta Mitra Sejati",
        keterangan: "ME",
        lokasi: "Jakarta",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Duta Permata Lestari",
        keterangan: "ME",
        lokasi: "Banjarmasin",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Dharma Karya Dhika alambana",
        keterangan: "ME",
        lokasi: "Jakarta",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Firefc Graha Sarana",
        keterangan: "ME",
        lokasi: "Jakarta",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Gatramas",
        keterangan: "ME",
        lokasi: "Jakarta",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Juhdi Sakti Engineering",
        keterangan: "ME",
        lokasi: "Jakarta",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Mandiri Jaya Teknik",
        keterangan: "ME",
        lokasi: "Makasar",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Perdana Abadi Perkasa",
        keterangan: "ME",
        lokasi: "Palembang",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Putra Masindo Utama",
        keterangan: "ME",
        lokasi: "Palembang",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Sentosa Abadi Suryatama",
        keterangan: "ME",
        lokasi: "Merauke",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Siam Karya Husan",
        keterangan: "ME",
        lokasi: "Banjarmasin",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Tirta Inti Drenthe",
        keterangan: "ME",
        lokasi: "Manado",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Tirta Putra Malindo",
        keterangan: "ME",
        lokasi: "Batam",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT War Besrendi",
        keterangan: "ME",
        lokasi: "Papua",
    },
    {
        jenis_usaha: "Kontraktor",
        customer_proyek: "PT Waskita Karya",
        keterangan: "ME",
        lokasi: "Jakarta",
    },
    {
        jenis_usaha: "Manufaktur",
        customer_proyek: "PT Amerta Indah Otsuka",
        keterangan: "pabrik Pocari Sweat",
        lokasi: "Sukabumi",
    },
    {
        jenis_usaha: "Manufaktur",
        customer_proyek: "PT Aristek High Polymer",
        keterangan: "pabrik kimia",
        lokasi: "Cikarang, Boro",
    },
    {
        jenis_usaha: "Manufaktur",
        customer_proyek: "PT Cabininfo Putra",
        keterangan: "pabrik mobil suzuki",
        lokasi: "Bekasi",
    },
    {
        jenis_usaha: "Manufaktur",
        customer_proyek: "PT Hung A Indonesia",
        keterangan: "pabrik ban swallow",
        lokasi: "Cikarang",
    },
    {
        jenis_usaha: "Manufaktur",
        customer_proyek: "PT Indofood Sukses Makmur",
        keterangan: "pabrik mie/makanan",
        lokasi: "Cikampek",
    },
    {
        jenis_usaha: "Manufaktur",
        customer_proyek: "PT Permata Dunia sukses Utama",
        keterangan: "pabrik gula",
        lokasi: "Serang-Banten",
    },
    {
        jenis_usaha: "Manufaktur",
        customer_proyek: "PT Sumber Cipta Multi Niaga",
        keterangan: "pabrik rokok djarum",
        lokasi: "Jakarta",
    },
    {
        jenis_usaha: "Manufaktur",
        customer_proyek: "PT Surya Multindo Indonesia",
        keterangan: "pabrik elektronik",
        lokasi: "Jababeka-Bekasi",
    },
    {
        jenis_usaha: "Manufaktur",
        customer_proyek: "PT URC Indonesia",
        keterangan: "pabrik makanan ringan",
        lokasi: "Cibitung-Bekasi",
    },
    {
        jenis_usaha: "Manufaktur",
        customer_proyek: "PT Urecel Indonesia",
        keterangan: "pabrik polyster",
        lokasi: "Cikarang-Bekasi",
    },
    {
        jenis_usaha: "Manufaktur",
        customer_proyek: "PT Wongjin",
        keterangan: "pabrik kimia",
        lokasi: "Kama",
    },
    {
        jenis_usaha: "Properti",
        customer_proyek: "Aston Hotel",
        keterangan: "hotel",
        lokasi: "Cikarang-Bekasi",
    },
    {
        jenis_usaha: "Properti",
        customer_proyek: "Bukit Sentul",
        keterangan: "Perumahan",
        lokasi: "Sentul-Bogor",
    },
    {
        jenis_usaha: "Properti",
        customer_proyek: "Cemara Hotel",
        keterangan: "hotel",
        lokasi: "Jakarta",
    },
    {
        jenis_usaha: "Properti",
        customer_proyek: "Kartika Plaza",
        keterangan: "hotel",
        lokasi: "Jakarta",
    },
    {
        jenis_usaha: "Properti",
        customer_proyek: "Esmeralda Golf Club",
        keterangan: "perumahan golf",
        lokasi: "Bogor",
    },
    {
        jenis_usaha: "Properti",
        customer_proyek: "PT Priamanaya Djan Int",
        keterangan: "pasar tanah abang blok a",
        lokasi: "Jakarta",
    },
    {
        jenis_usaha: "Properti",
        customer_proyek: "Water Boom Lippo",
        keterangan: "water park",
        lokasi: "Cikarang, Bekasi",
    },
    {
        jenis_usaha: "Rumah Sakit",
        customer_proyek: "RS Puri Cinere",
        keterangan: "rumah sakit",
        lokasi: "Jakarta",
    },
    {
        jenis_usaha: "Rumah Sakit",
        customer_proyek: "RS Siloam Gleneagles",
        keterangan: "rumah sakit",
        lokasi: "Cikarang, Bekasi",
    },
    {
        jenis_usaha: "Rumah Sakit",
        customer_proyek: "RS Permata Cibubur",
        keterangan: "rumah sakit",
        lokasi: "Jakarta",
    },
    {
        jenis_usaha: "Sekolah",
        customer_proyek: "YP Pelita Harapan International",
        keterangan: "sekolah",
        lokasi: "Serpong, Banten",
    },
    {
        jenis_usaha: "Sekolah",
        customer_proyek: "YPI Al Azhar",
        keterangan: "sekolah",
        lokasi: "Jakarta",
    },
];

export default portfolios
